name = "vocal-app-r2-upload"
main = "cloudflare-worker.js"
compatibility_date = "2026-08-09"

[[r2_buckets]]
binding = "VOCAL_APP_STORAGE"
bucket_name = "vocal-app-storage"

[vars]
R2_PUBLIC_URL = "https://vocal-app-r2-upload.caminante-via.workers.dev"
